### ISSUE TITLE
可否加微信联系下？

### ISSUE THREAD

**Issue by hirokith** [RizzleCi/blog#6]
😀你好，最近考虑新的工作机会吗？阿里飞猪北京前端团队急招高级前端（P6）和前端专家（P7），业务发展空间大，团队技术氛围好，有兴趣期待加微信联系 Dickeylth，谢谢！

**Comment by thjiang** [comment]
> 😀你好，最近考虑新的工作机会吗？阿里飞猪北京前端团队急招高级前端（P6）和前端专家（P7），业务发展空间大，团队技术氛围好，有兴趣期待加微信联系 Dickeylth，谢谢！

不用想了，小姐姐刚换过工作😂

**Comment by hirokith** [comment]
> > 😀你好，最近考虑新的工作机会吗？阿里飞猪北京前端团队急招高级前端（P6）和前端专家（P7），业务发展空间大，团队技术氛围好，有兴趣期待加微信联系 Dickeylth，谢谢！
> 
> 不用想了，小姐姐刚换过工作😂

这样……🤣，好吧……
